<style>
    footer {
        background-color: #FFF;
        color: black;
        font-size:9px;
        text-align: center;
        padding: 20px;
        margin-top: 20px;
    }
    
    footer a {
        color: #fff;
    }
</style>

<footer>
    <p>&copy; 2025 SGVendas. Todos os direitos reservados.</p>
    <p>
        Valter Barreto - 
        <i class="fas fa-phone"></i> (81) 9 8842-1455 - 
        <i class="fas fa-envelope"></i> valterpb@gmail.com - Licenciado para uso da Imobiliária Tocca Onze Nov/2025
    </p>
</footer>